[pytest]
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
asyncio_mode = auto
addopts = -v --tb=short --timeout=20 -m "not external and not slow"
markers =
    asyncio: mark test as async
    slow: marks tests as slow (deselect with '-m "not slow"')
    external: marks tests that require real hardware/system/environment (deselect with '-m "not external"')
